#Botones
COLOR_BTN = "#b9b8b8"
COLOR_BTN_CONFIRMACION = "#fa8078"
COLOR_BORDE_BTN = "#666666"

COLOR_BTN_INSTRUCIONES = "#65aef5"
COLOR_BORDE_INSTRUCIONES = "#4a96e0"

#Click
COLOR_CURSOR_ENCIMA = "#2bdefa"

#Fondos
COLOR_BACKGROUND = "#dce1e2"
COLOR_PANEL = "#b7b8b8"
COLOR_BACKGROUND_IMAGENES = "#ffffff"
COLOR_BORDE_LOGO = "#9e9c9c"

#Matriz
COLOR_MATRIZ = "#e5e6e6"
COLOR_BLANCO = "#ffffff"