#Botones
COLOR_BTN = "#b9b8b8"
COLOR_BTN_CONFIRMACION = "#fa8078"
COLOR_BORDE_BTN = "#666666"

#Click
COLOR_CURSOR_ENCIMA = "#2bdefa"

#Fondos
COLOR_BACKGROUND = "#dce1e2"
COLOR_PANEL = "#b7b8b8"
COLOR_BACKGROUND_IMAGENES = "#ffffff"
COLOR_BORDE_LOGO = "#9e9c9c"
